create schema if not exists private;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  name text not null,
  first_name text,
  last_name text,
  phone_number text,
  image_url text,
  role text not null default 'user' check (role in ('admin', 'user')),
  status text not null default 'pending' check (status in ('pending', 'active', 'suspended')),
  template_access text not null default 'custom' check (template_access in ('all', 'custom')),
  allowed_template_ids text[] not null default '{}',
  feature_access text[] not null default '{}',
  access_starts_at timestamptz,
  access_ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_data (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  storage_key text not null check (storage_key in (
    'mc011-invoice-editor-v1',
    'mc011-data-splitter-projects-v1',
    'mc011-supplier-profile-overrides-v1'
  )),
  payload jsonb,
  byte_length integer not null default 0 check (byte_length >= 0),
  active_template_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, storage_key)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid not null references public.profiles(id) on delete cascade,
  target_user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  details jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null default '',
  status text not null default 'backlog' check (status in ('backlog', 'in_progress', 'review', 'done')),
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high', 'urgent')),
  assignee text not null default 'Unassigned',
  due_date date,
  labels text[] not null default '{}',
  created_by text not null,
  updated_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.presence (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  name text not null,
  color text not null,
  last_seen timestamptz not null default now()
);

create or replace function private.is_active_user()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid())
      and p.status = 'active'
      and (p.access_starts_at is null or p.access_starts_at <= now())
      and (p.access_ends_at is null or p.access_ends_at >= now())
  );
$$;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid())
      and p.role = 'admin'
      and p.status = 'active'
      and (p.access_starts_at is null or p.access_starts_at <= now())
      and (p.access_ends_at is null or p.access_ends_at >= now())
  );
$$;

create or replace function private.can_use_template(template_id text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select template_id is null or exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid())
      and p.status = 'active'
      and (p.access_starts_at is null or p.access_starts_at <= now())
      and (p.access_ends_at is null or p.access_ends_at >= now())
      and (p.role = 'admin' or p.template_access = 'all' or template_id = any(p.allowed_template_ids))
  );
$$;

create or replace function private.provision_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  bootstrap_admin boolean;
  first_name_value text;
  last_name_value text;
  full_name_value text;
begin
  select not exists (select 1 from public.profiles) into bootstrap_admin;
  first_name_value := nullif(trim(coalesce(new.raw_user_meta_data ->> 'first_name', '')), '');
  last_name_value := nullif(trim(coalesce(new.raw_user_meta_data ->> 'last_name', '')), '');
  full_name_value := nullif(trim(coalesce(new.raw_user_meta_data ->> 'full_name', '')), '');
  insert into public.profiles (
    id, email, name, first_name, last_name, phone_number, image_url,
    role, status, template_access, feature_access
  ) values (
    new.id,
    lower(coalesce(new.email, '')),
    coalesce(full_name_value, nullif(split_part(coalesce(new.email, ''), '@', 1), ''), 'Invoice user'),
    first_name_value,
    last_name_value,
    nullif(trim(coalesce(new.raw_user_meta_data ->> 'phone_number', '')), ''),
    nullif(trim(coalesce(new.raw_user_meta_data ->> 'avatar_url', '')), ''),
    case when bootstrap_admin then 'admin' else 'user' end,
    case when bootstrap_admin then 'active' else 'pending' end,
    case when bootstrap_admin then 'all' else 'custom' end,
    case when bootstrap_admin then array['bulkInvoiceGenerator','dataCleaning','manualDataCleaning','metadataRemover','pdfCompressor']::text[] else '{}'::text[] end
  ) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.provision_profile();

create or replace function public.ensure_current_user(
  p_name text,
  p_first_name text default null,
  p_last_name text default null,
  p_phone_number text default null,
  p_image_url text default null
)
returns public.profiles
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := auth.uid();
  result public.profiles;
begin
  if uid is null then raise exception 'You must be signed in.'; end if;
  update public.profiles set
    email = lower(coalesce((select email from auth.users where id = uid), email)),
    name = coalesce(nullif(trim(p_name), ''), name),
    first_name = coalesce(nullif(trim(p_first_name), ''), first_name),
    last_name = coalesce(nullif(trim(p_last_name), ''), last_name),
    phone_number = coalesce(nullif(trim(p_phone_number), ''), phone_number),
    image_url = coalesce(nullif(trim(p_image_url), ''), image_url),
    updated_at = now()
  where id = uid
  returning * into result;
  if result.id is null then raise exception 'Your account profile is unavailable.'; end if;
  return result;
end;
$$;

create or replace function public.admin_update_user_access(
  p_user_id uuid,
  p_role text,
  p_status text,
  p_template_access text,
  p_allowed_template_ids text[],
  p_feature_access text[],
  p_access_starts_at timestamptz default null,
  p_access_ends_at timestamptz default null
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := auth.uid();
begin
  if not private.is_admin() then raise exception 'Administrator access is required.'; end if;
  if p_role not in ('admin','user') or p_status not in ('pending','active','suspended') or p_template_access not in ('all','custom') then
    raise exception 'Invalid access settings.';
  end if;
  if p_access_starts_at is not null and p_access_ends_at is not null and p_access_ends_at < p_access_starts_at then
    raise exception 'The access end date cannot be before the start date.';
  end if;
  if p_user_id = uid and (p_role <> 'admin' or p_status <> 'active' or (p_access_starts_at is not null and p_access_starts_at > now()) or (p_access_ends_at is not null and p_access_ends_at < now())) then
    raise exception 'You cannot remove, suspend, schedule, or expire your own administrator access.';
  end if;
  update public.profiles set
    role = p_role,
    status = p_status,
    template_access = p_template_access,
    allowed_template_ids = coalesce((select array_agg(distinct value) from unnest(coalesce(p_allowed_template_ids, '{}'::text[])) value), '{}'::text[]),
    feature_access = coalesce((select array_agg(distinct value) from unnest(coalesce(p_feature_access, '{}'::text[])) value), '{}'::text[]),
    access_starts_at = p_access_starts_at,
    access_ends_at = p_access_ends_at,
    updated_at = now()
  where id = p_user_id;
  if not found then raise exception 'User not found.'; end if;
  insert into public.audit_logs(actor_user_id, target_user_id, action, details)
  values (uid, p_user_id, 'user_access_updated', jsonb_build_object(
    'role', p_role, 'status', p_status, 'templateAccess', p_template_access,
    'allowedTemplateIds', p_allowed_template_ids, 'featureAccess', p_feature_access,
    'accessStartsAt', p_access_starts_at, 'accessEndsAt', p_access_ends_at
  ));
  return true;
end;
$$;

alter table public.profiles enable row level security;
alter table public.user_data enable row level security;
alter table public.audit_logs enable row level security;
alter table public.tasks enable row level security;
alter table public.presence enable row level security;

revoke all on public.profiles, public.user_data, public.audit_logs, public.tasks, public.presence from anon;
revoke insert, update, delete on public.profiles from authenticated;
grant select on public.profiles to authenticated;
grant select, insert, update, delete on public.user_data, public.tasks, public.presence to authenticated;
grant select on public.audit_logs to authenticated;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated
using (id = (select auth.uid()) or private.is_admin());

drop policy if exists user_data_select on public.user_data;
create policy user_data_select on public.user_data for select to authenticated
using (user_id = (select auth.uid()) and private.is_active_user());
drop policy if exists user_data_insert on public.user_data;
create policy user_data_insert on public.user_data for insert to authenticated
with check (user_id = (select auth.uid()) and private.is_active_user() and private.can_use_template(active_template_id));
drop policy if exists user_data_update on public.user_data;
create policy user_data_update on public.user_data for update to authenticated
using (user_id = (select auth.uid()) and private.is_active_user())
with check (user_id = (select auth.uid()) and private.is_active_user() and private.can_use_template(active_template_id));
drop policy if exists user_data_delete on public.user_data;
create policy user_data_delete on public.user_data for delete to authenticated
using (user_id = (select auth.uid()) and private.is_active_user());

drop policy if exists audit_logs_select on public.audit_logs;
create policy audit_logs_select on public.audit_logs for select to authenticated using (private.is_admin());

drop policy if exists tasks_select on public.tasks;
create policy tasks_select on public.tasks for select to authenticated using (private.is_active_user());
drop policy if exists tasks_insert on public.tasks;
create policy tasks_insert on public.tasks for insert to authenticated with check (private.is_active_user());
drop policy if exists tasks_update on public.tasks;
create policy tasks_update on public.tasks for update to authenticated using (private.is_active_user()) with check (private.is_active_user());
drop policy if exists tasks_delete on public.tasks;
create policy tasks_delete on public.tasks for delete to authenticated using (private.is_active_user());

drop policy if exists presence_select on public.presence;
create policy presence_select on public.presence for select to authenticated using (private.is_active_user());
drop policy if exists presence_insert on public.presence;
create policy presence_insert on public.presence for insert to authenticated with check (user_id = (select auth.uid()) and private.is_active_user());
drop policy if exists presence_update on public.presence;
create policy presence_update on public.presence for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()) and private.is_active_user());
drop policy if exists presence_delete on public.presence;
create policy presence_delete on public.presence for delete to authenticated using (user_id = (select auth.uid()));

revoke all on function public.ensure_current_user(text,text,text,text,text) from public, anon;
grant execute on function public.ensure_current_user(text,text,text,text,text) to authenticated;
revoke all on function public.admin_update_user_access(uuid,text,text,text,text[],text[],timestamptz,timestamptz) from public, anon;
grant execute on function public.admin_update_user_access(uuid,text,text,text,text[],text[],timestamptz,timestamptz) to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 5242880, array['image/png','image/jpeg','image/webp','image/gif'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists avatar_insert_own on storage.objects;
create policy avatar_insert_own on storage.objects for insert to authenticated
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);
drop policy if exists avatar_update_own on storage.objects;
create policy avatar_update_own on storage.objects for update to authenticated
using (bucket_id = 'avatars' and owner_id = (select auth.uid())::text)
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);
drop policy if exists avatar_delete_own on storage.objects;
create policy avatar_delete_own on storage.objects for delete to authenticated
using (bucket_id = 'avatars' and owner_id = (select auth.uid())::text);

do $$
begin
  alter publication supabase_realtime add table public.tasks;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.presence;
exception when duplicate_object then null;
end $$;
